<?php

namespace zer0latency\KladrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KladrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KladrRepository extends EntityRepository
{
}
